using System;
using Godot;

namespace AoS;

// (Partially) Generated by GPT-5 mini
public partial class Health : Resource
{
    private const string ScriptPath = "scripts/health.gd";

    // Typed properties that proxy into the GDScript resource
    public int MaxHealth
    {
        get => Get("max_health").AsInt32();
        set => Set("max_health", value);
    }

    public int CurrentHealth
    {
        get => Get("health").AsInt32();
        set => Set("health", value);
    }

    // C# events that mirror the GDScript signals (carry the new int value)
    [Signal] public delegate void MaxHealthChangedEventHandler(int newHealth);
    [Signal] public delegate void HealedEventHandler(int newHealth);
    [Signal] public delegate void DamagedEventHandler(int newHealth);
    [Signal] public delegate void ReplenishedEventHandler(int newHealth);
    [Signal] public delegate void DepletedEventHandler(int newHealth);

    public static StringName MaxHealthChangedSignal = "max_health_changed";
    public static StringName HealedSignal = "healed";
    public static StringName DamagedSignal = "damaged";
    public static StringName ReplenishedSignal = "replenished";
    public static StringName DepletedSignal = "depleted";

    public Health()
    {
        Script script = ResourceLoader.Load<Script>(ScriptPath);
        SetScript(script);
    }
}

